In [2]:
from __future__ import print_function, division

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

# Load and filter the data

In [4]:
brooklyn_df = pd.read_csv("../data/foodtruck_df.csv.zip")

top_10_stations = \
    list(brooklyn_df.groupby('UNIQUE_STATION').DAILY_TOTAL.sum().sort_values(ascending=False)[:10].index)

# Extract the data for the top 10 stations
top_10_df = brooklyn_df[brooklyn_df.UNIQUE_STATION.isin(top_10_stations)]

top_10_by_station_and_day = top_10_df.groupby(['UNIQUE_STATION', 'DAY_OF_WEEK']).DAILY_TOTAL.median()
# Turn the series back into a DataFrame
top_10_by_station_and_day = top_10_by_station_and_day.reset_index()

top_10_by_station_and_day

/usr/local/anaconda3/envs/metis-bootcamp/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

              UNIQUE_STATION DAY_OF_WEEK  DAILY_TOTAL
0                     8 AV N      Friday       1080.5
1                     8 AV N      Monday       1163.0
2                     8 AV N    Saturday        664.0
3                     8 AV N      Sunday        652.0
4                     8 AV N    Thursday       1033.5
5                     8 AV N     Tuesday       1219.0
6                     8 AV N   Wednesday       1197.0
7                    86 ST R      Friday        481.0
8                    86 ST R      Monday        464.0
9                    86 ST R    Saturday        163.0
10                   86 ST R      Sunday        132.0
11                   86 ST R    Thursday        510.0
12                   86 ST R     Tuesday        515.0
13                   86 ST R   Wednesday        515.0
14  ATL AV-BARCLAY 2345BDNQR      Friday        299.5
15  ATL AV-BARCLAY 2345BDNQR      Monday        290.5
16  ATL AV-BARCLAY 2345BDNQR    Saturday         63.0
17  ATL AV-BARCLAY 2345BDNQR      Sunday         57.0
18  ATL AV-BARCLAY 2345BDNQR    Thursday        296.0
19  ATL AV-BARCLAY 2345BDNQR     Tuesday        295.5
20  ATL AV-BARCLAY 2345BDNQR   Wednesday        338.5
21  ATL AV-BARCLAY BDNQR2345      Friday        333.5
22  ATL AV-BARCLAY BDNQR2345      Monday        307.0
23  ATL AV-BARCLAY BDNQR2345    Saturday        160.0
24  ATL AV-BARCLAY BDNQR2345      Sunday        132.0
25  ATL AV-BARCLAY BDNQR2345    Thursday        310.5
26  ATL AV-BARCLAY BDNQR2345     Tuesday        353.0
27  ATL AV-BARCLAY BDNQR2345   Wednesday        365.0
28              BEDFORD AV L      Friday       1114.0
29              BEDFORD AV L      Monday       1066.0
..                       ...         ...          ...
40        BOROUGH HALL 2345R     Tuesday        704.5
41        BOROUGH HALL 2345R   Wednesday        711.5
42        CROWN HTS-UTICA 34      Friday        713.0
43        CROWN HTS-UTICA 34      Monday        707.0
44        CROWN HTS-UTICA 34    Saturday        337.0
45        CROWN HTS-UTICA 34      Sunday        258.5
46        CROWN HTS-UTICA 34    Thursday        731.0
47        CROWN HTS-UTICA 34     Tuesday        720.0
48        CROWN HTS-UTICA 34   Wednesday        752.0
49       JAY ST-METROTEC ACF      Friday        526.0
50       JAY ST-METROTEC ACF      Monday        485.0
51       JAY ST-METROTEC ACF    Saturday        179.0
52       JAY ST-METROTEC ACF      Sunday        145.0
53       JAY ST-METROTEC ACF    Thursday        570.0
54       JAY ST-METROTEC ACF     Tuesday        571.0
55       JAY ST-METROTEC ACF   Wednesday        571.0
56              KINGS HWY BQ      Friday        695.0
57              KINGS HWY BQ      Monday        656.5
58              KINGS HWY BQ    Saturday        248.5
59              KINGS HWY BQ      Sunday        216.5
60              KINGS HWY BQ    Thursday        770.0
61              KINGS HWY BQ     Tuesday        718.0
62              KINGS HWY BQ   Wednesday        764.0
63         MYRTLE-WYCKOFF LM      Friday        664.0
64         MYRTLE-WYCKOFF LM      Monday        609.0
65         MYRTLE-WYCKOFF LM    Saturday        295.0
66         MYRTLE-WYCKOFF LM      Sunday        232.0
67         MYRTLE-WYCKOFF LM    Thursday        657.0
68         MYRTLE-WYCKOFF LM     Tuesday        729.0
69         MYRTLE-WYCKOFF LM   Wednesday        730.0

[70 rows x 3 columns]

# Create the data table

In [6]:
traffic_by_station_and_day = \
    pd.pivot_table(top_10_by_station_and_day, values='DAILY_TOTAL', index='UNIQUE_STATION', columns='DAY_OF_WEEK')

# Re-order the columns
traffic_by_station_and_day = \
    traffic_by_station_and_day[['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']]

traffic_by_station_and_day

DAY_OF_WEEK,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday
UNIQUE_STATION,,,,,,,
8 AV N,1163.0,1219.0,1197.0,1033.5,1080.5,664.0,652.0
86 ST R,464.0,515.0,515.0,510.0,481.0,163.0,132.0
ATL AV-BARCLAY 2345BDNQR,290.5,295.5,338.5,296.0,299.5,63.0,57.0
ATL AV-BARCLAY BDNQR2345,307.0,353.0,365.0,310.5,333.5,160.0,132.0
BEDFORD AV L,1066.0,1149.0,1176.0,1178.0,1114.0,289.0,229.0
BOROUGH HALL 2345R,628.0,704.5,711.5,714.0,645.5,126.5,91.5
CROWN HTS-UTICA 34,707.0,720.0,752.0,731.0,713.0,337.0,258.5
JAY ST-METROTEC ACF,485.0,571.0,571.0,570.0,526.0,179.0,145.0
KINGS HWY BQ,656.5,718.0,764.0,770.0,695.0,248.5,216.5
MYRTLE-WYCKOFF LM,609.0,729.0,730.0,657.0,664.0,295.0,232.0

Create the